import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfGenerator {
  /// Generate Mieterprofil (tenant profile) PDF
  static Future<void> generateMieterprofil({
    required String name,
    required String dob,
    required String phone,
    required String email,
    required String address,
    required String employer,
    required String income,
    required String occupants,
    String? pets,
    String? rentalDuration,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          // Header
          pw.Header(
            level: 0,
            child: pw.Text('Mieterprofil', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
          ),
          pw.SizedBox(height: 8),
          pw.Text('Tenant Profile for Rental Applications', style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600)),
          pw.Divider(),
          pw.SizedBox(height: 16),

          // Personal Information
          _sectionHeader('Persönliche Daten / Personal Information'),
          _infoRow('Name', name),
          _infoRow('Geburtsdatum / Date of Birth', dob),
          _infoRow('Telefon / Phone', phone),
          _infoRow('E-Mail', email),
          _infoRow('Adresse / Address', address),
          pw.SizedBox(height: 16),

          // Employment
          _sectionHeader('Beruf / Employment'),
          _infoRow('Arbeitgeber / Employer', employer),
          _infoRow('Nettoeinkommen / Net Income', '$income EUR/month'),
          pw.SizedBox(height: 16),

          // Household
          _sectionHeader('Haushalt / Household'),
          _infoRow('Personenanzahl / Number of Occupants', occupants),
          if (pets != null && pets.isNotEmpty)
            _infoRow('Haustiere / Pets', pets),
          if (rentalDuration != null && rentalDuration.isNotEmpty)
            _infoRow('Gewünschte Mietdauer / Desired Rental Duration', rentalDuration),
          pw.SizedBox(height: 24),

          // Footer
          pw.Divider(),
          pw.SizedBox(height: 8),
          pw.Text(
            'Dieses Dokument wurde erstellt von EuroRent Lens.',
            style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
          ),
          pw.Text(
            'Generated by EuroRent Lens — AI-powered rental analysis.',
            style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) async => pdf.save(),
      name: 'Mieterprofil_$name',
    );
  }

  /// Generate rental contract template
  static Future<void> generateRentalContract({
    required String landlordName,
    required String tenantName,
    required String address,
    required String rentAmount,
    required String startDate,
    String? endDate,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text('Mietvertrag', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
          ),
          pw.SizedBox(height: 8),
          pw.Text('Rental Agreement', style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600)),
          pw.Divider(),
          pw.SizedBox(height: 16),

          _sectionHeader('Parteien / Parties'),
          _infoRow('Vermieter / Landlord', landlordName),
          _infoRow('Mieter / Tenant', tenantName),
          pw.SizedBox(height: 16),

          _sectionHeader('Mietobjekt / Rental Property'),
          _infoRow('Adresse / Address', address),
          pw.SizedBox(height: 16),

          _sectionHeader('Konditionen / Terms'),
          _infoRow('Miete / Rent', '$rentAmount EUR/month'),
          _infoRow('Beginn / Start Date', startDate),
          if (endDate != null && endDate.isNotEmpty)
            _infoRow('Ende / End Date', endDate),
          if (endDate == null || endDate.isEmpty)
            _infoRow('Laufzeit / Duration', 'Unbefristet / Indefinite'),
          pw.SizedBox(height: 24),

          pw.Divider(),
          pw.SizedBox(height: 16),
          pw.Text('Ort, Datum / Place, Date: ____________________'),
          pw.SizedBox(height: 24),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Unterschrift Vermieter'),
                  pw.Text('Signature Landlord'),
                  pw.SizedBox(height: 30),
                  pw.Container(width: 200, height: 1, color: PdfColors.black),
                ],
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Unterschrift Mieter'),
                  pw.Text('Signature Tenant'),
                  pw.SizedBox(height: 30),
                  pw.Container(width: 200, height: 1, color: PdfColors.black),
                ],
              ),
            ],
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) async => pdf.save(),
      name: 'Mietvertrag',
    );
  }

  /// Generate income certificate
  static Future<void> generateIncomeCertificate({
    required String employeeName,
    required String employerName,
    required String monthlyIncome,
    required String employmentStart,
    String? position,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text('Einkommensbescheinigung', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
          ),
          pw.SizedBox(height: 8),
          pw.Text('Income Certificate', style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600)),
          pw.Divider(),
          pw.SizedBox(height: 24),

          pw.Text(
            'Hiermit wird bestätigt, dass:',
            style: pw.TextStyle(fontSize: 12),
          ),
          pw.SizedBox(height: 16),

          pw.Text(
            'This is to certify that:',
            style: pw.TextStyle(fontSize: 11, color: PdfColors.grey600),
          ),
          pw.SizedBox(height: 12),

          _infoRow('Name', employeeName),
          if (position != null)
            _infoRow('Position', position),
          _infoRow('Arbeitgeber / Employer', employerName),
          _infoRow('Beschäftigt seit / Employed since', employmentStart),
          _infoRow('Monatliches Nettoeinkommen / Monthly Net Income', '$monthlyIncome EUR'),
          pw.SizedBox(height: 24),

          pw.Text(
            'Dieses Zeugnis wird auf Anfrage des Arbeitnehmers ausgestellt '
            'und dient ausschließlich der Vorlage bei Mietvertragsverhandlungen.',
            style: pw.TextStyle(fontSize: 11),
          ),
          pw.Text(
            'This certificate is issued at the request of the employee '
            'and is intended solely for presentation during rental negotiations.',
            style: pw.TextStyle(fontSize: 11, color: PdfColors.grey600),
          ),
          pw.SizedBox(height: 32),

          pw.Divider(),
          pw.SizedBox(height: 8),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Ort, Datum'),
                  pw.SizedBox(height: 30),
                  pw.Container(width: 200, height: 1, color: PdfColors.black),
                  pw.Text('Unterschrift Arbeitgeber'),
                ],
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Stempel / Stamp'),
                  pw.SizedBox(height: 30),
                  pw.Container(
                    width: 100,
                    height: 100,
                    decoration: pw.BoxDecoration(
                      border: pw.Border.all(color: PdfColors.grey400),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) async => pdf.save(),
      name: 'Einkommensbescheinigung',
    );
  }

  static pw.Widget _sectionHeader(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 10),
      decoration: pw.BoxDecoration(
        color: PdfColors.blue50,
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Text(text, style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
    );
  }

  static pw.Widget _infoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 200,
            child: pw.Text(label, style: pw.TextStyle(fontSize: 11, color: PdfColors.grey700)),
          ),
          pw.Expanded(
            child: pw.Text(value, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
          ),
        ],
      ),
    );
  }
}
